version: '3'

services:

  gateway:
    restart: always
    image: azsuth/beefy-gainz-gateway:latest
    ports: 
      - 3001:3001

  router:
    restart: always
    image: azsuth/beefy-gainz-router:latest

  client:
    image: azsuth/beefy-gainz-client:latest

  config:
    image: azsuth/beefy-gainz-config:latest
    environment: 
      - SPRING_PROFILES_ACTIVE=qa
      
  exercise:
    restart: always
    image: azsuth/beefy-gainz-exercise:latest
    environment:
      - SPRING_PROFILES_ACTIVE=qa